### ISSUE TITLE
Add support for 415 Unsupported Media Type when content type is not indicated correctly

### ISSUE THREAD

**Issue by ozanyasindogan** [tdeleon/Relax#31]
This is the http error I got when I forgot to add content type to the request headers so it would be nice to handle it separately inside Errors I believe and give a friendly error message. I had to spend some time to figure out what's the problem because it was returning a deserialisation error.

**Comment by tdeleon** [comment]
@ozanyasindogan - thanks for the suggestion! I've added this error type to the develop branch, and it should be in the next release.

**Comment by ozanyasindogan** [comment]
> @ozanyasindogan - thanks for the suggestion! I've added this error type to the develop branch, and it should be in the next release.

thank you for this great library, it saved me a lot of boilerplate code..
